services:
  postgres:
    image: postgres:16-alpine
    restart: unless-stopped
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: kurnik
      POSTGRES_PASSWORD: kurnik
      POSTGRES_DB: kurnik_sopa
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
